default: &default
  test: '1'
  first_level_catalogs:     ['关于本使用说明书', '操作', '安全', '驾驶指南', '维护指南', '自救', '技术数据']
  noise_right_side_begin:   10000
  is_increment:             true #增量插入.

Audi+A4L+B8_cn.pdf:
  <<: *default
  car_make:                 奥迪
  car_line:                 奥迪A4
  year:                     2013
  catatlog_pages:           [4, 5, 6]
  noise_head_height:        495.3293 #一个页面中， 头部的高度 既是y轴
  noise_footer_height:      73.2293  #footer的高度
  page_title_height:        468.0293 #的高度
  page_title_size:          12       
  catalog_1_size:           9
  catalog_2_size:           7
  catalog_3_size:           6
  catalog_2_content_size:   12 #在一个页面中， 一个2级目录文字的字体是12
  catalog_3_content_size:   10 #在一个页面中， 一个3级目录文字的字体是10
  catalog_4_content_size:   9  #在一个页面中， 一个4级目录文字的字体是9
  first_children_begin:     433.68 #页面中 第一子页面的开始横坐标
  second_children_begin:    694.4999 #页面中 第二子页面的开始横坐标
  children_page_width:      216 #子页面的宽度
  content_begin_page:       26
  pic_save:                 false
  pic_force_save:           false
  not_fourth_nodes:         ['说明', '警告！' ]
  save_db:                  false
Audi+A6L+C7_cn.pdf:
  <<: *default
  car_make:                 奥迪
  car_line:                 奥迪A6
  year:                     2010  #不确定这个 pdf的年
  catatlog_pages:           [2, 3, 4]
  noise_head_height:        7000  #此pdf head 没有内容
  noise_footer_height:      73.2293
  page_title_height:        600.438
  noise_right_side_begin:   448.7788
  first_children_begin:     77.1019 #页面中 第一子页面的开始横坐标
  first_children_end:       231.5671 #页面中 第一子页面的结束横坐标
  second_children_begin:    259.6513 #页面中 第二子页面的开始横坐标
  second_children_end:      414.4098 #页面中 第二子页面的结束横坐标
  children_page_width:      154.65000000000003 #子页面的宽度
  page_title_size:          11
  catalog_1_size:           9
  catalog_2_size:           7
  catalog_3_size:           6
  catalog_3_content_size:   11 #在一个页面中， 一个3级目录文字的字体是11
  catalog_4_content_size:   7  #在一个页面中， 一个3级目录文字的字体是7
  content_begin_page:       220
  content_end_page:         227
  pic_save:                 false
  save_db:                  false
  pic_force_save:           true
  is_production:            true #如果为true 存入到 服务器的db
  not_fourth_nodes:         ['1140 1165 1165 1165', '前', '上述所列数据是在未安装影响整车性能的设备(如空调', '132KW 2245 2270 1770 1800', '6', '保险丝位置分配', '11辅驱动助)加热装置/LIN继电器(混合 5', '1收', '10左大灯(装有自适应车灯的大灯) 7.5', '5芯片卡读卡器(取决于不同国家) 5', '9光', '6电动座椅调节装置(副驾驶员侧) 7.5', '5座椅电动调节装置(驾驶员座椅) 7.5', '14仪表板(副驾驶员侧)内 15号接线柱 30',  '8副', '225/60R1698Y', 'R径向的子午线轮胎结构标记字母',  '98载重能力参数', '轮辋规格压入深度(ET)轮胎规格', '松开防盗车轮螺栓时需要一个专用适配接头', '限制', '变速箱:请踩制动器并重新挂入行驶档', '从档位 D/S短促向后拉选档杆以便挂入 S',  '以超过存储的车速值 10 km/h以上的速度行驶五', '如图将无线遥控钥匙按在标记出的部位', '点火开关已打开', '时上锁', '钥匙不在车内？', '钥匙识别', '腰部支撑调节和按摩功能', '操作要领', '或', '大灯照明距离自动调节装置只有一个辅助功', '能在接下来的 45秒内能用钥匙给所有车门和', '警告！', '提示', '小心', '警告', '低温区', '环保指南', '请松开驻车制动器', '正常区', '见使用说明书', '能存在发生交通事故时无法激活该系统的危', '2.游标指示灯和驾驶指南', '4.游标音频/视频', '持续显示外界温度、时间、变速箱档位、单次行', '切勿利用车外温度显示结果来判断路面上是否', '在菜单的车辆功能选项下选择车载计算机或功', '如要在节能指南出现后的瞬间屏蔽节能指南显', '黄色圆圈图 12换高/低档', '在信息娱乐系统中可以调节日期、时间、时间', '开关后在组合仪表显示屏中出现一条驾驶指南', '在汽车附近如有相同频率工作的发射器(如移动', '发动机或操作电动设备(例如电动车窗升降', '或者']
  is_fourth_nodes:          ['保险丝位置分配，驾驶舱驾驶员侧', '保险丝位置分配，驾驶舱副驾驶员侧']
  status:                   ['提示', '警告', '小心', '环境保护指南', '环保指南']
  catalog_destription_size: 6 #目录描述 '适用于:'
  bold_font_size:           8 #加粗字体 
  same_garagraph_distance:  12 #是同一行的 间隔
  generate_catalogs:        true #用于生成所有的目录， 因为A6的目录有点特殊， 需要人工审核