source 'http://ruby.taobao.org'

gem 'pdf-reader'

gem 'sinatra-static-assets'
gem 'sinatra'
gem 'activesupport', '4.1.4'
gem 'thin'

gem 'pry-nav'
gem 'pry'
gem 'activerecord'
gem 'mysql2'
gem 'redcarpet'
gem 'carrierwave-qiniu'
gem 'slim'
gem 'linguo'
gem "mini_magick"
gem 'nokogiri'
