default: &default
  test: '1'
Audi+A4L+B8_cn.pdf:
  <<: *default
  catatlog_pages:           [4, 5, 6]
  noise_head_height:        495.3293
  noise_footer_height:      73.2293
  page_title_height:        468.0293
  page_number_offset:       2
  catalog_1_size:           9
  catalog_2_size:           7
  catalog_3_size:           6
  content_begin_page:       12
  not_fourth_nodes:         ['说明', '警告！' ]